### ISSUE TITLE
server.js task is unclear

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/express-and-testing-workshop#10]
@Akin909 ended up casting the solution so that students could move forward

It's not overly clear what students are being asked to do. Some of them seemed surprised that they were only being asked to write these 2 lines. Others didn't understand exactly what was happening here.

It would help to
+ [ ] have clear instructions in the readme, rather than the file itself
+ [ ] walk students through the existing codebase before setting them a task

### Getting students to write `app.use(bodyParser.json());`
In the readme:
> inside server.js require in any necessary middleware

How should students know what middleware is necessary at this point?

Then, in the `server.js` file itself:
> We need middleware to convert request and response payloads to an from JSON

### Getting students to write `app.use('/v1/api/', routes);`
Then, in the `server.js` file itself:
> We need to setup a route/collection of routes

and this is sort of in [the introduction section](https://github.com/Akin909/express-and-testing-workshop/tree/master#introduction) of the readme
> // In Server.js
> const app = express()
> app.use('/api/v1/', routes)

The fact that students didn't know what to do was partly caused by the confusion around step 13 (modularisation) in [day 1's code along](https://github.com/foundersandcoders/express-workshop).

After casting the solution, the verbal feedback from students was:
> I don't really know what this line is doing
>
> Can you do this on one line?
>
> Why are you pointing to a whole folder instead of a file?

(i.e. `const routes = require('./routes');`)

**Comment by arrested-developer** [comment]
Agreed, the 'hints' in the server.js threw most of our cohort and as far as I'm concerned, wasted time that could have been used writing database tests, which was practise that FAC14 desperately needed.
