### ISSUE TITLE
clarify what tests students are supposed to be writing

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/express-and-testing-workshop#11]
There are no real instructions for the actual tasks that students are supposed to complete in this workshop

+ [ ] Add instructions to readme

How should students know they are supposed to reach [this solution](https://github.com/Akin909/express-and-testing-workshop/blob/solution-branch/server/tests/routes.test.js) from:
> Fill this with many many tests YAY!!

Some verbal responses from FAC11
> Where do I start?
>
> So what am I supposed to test?

This made it necessary for @Akin909 and @PiotrBerebecki to float around the room, providing a lot of verbal instruction and explanation.

Most students were therefore looking at the solutions branch to figure out what to write. This doesn't really teach them to reason about what tests they would write for themselves. Using the solution branch to figure it out led to questions like:
> Why am I testing whether an array is an array?
>
> What's a good thing to test?
>
> With the POST request, what are you wanting us to test?

**Comment by m4v15** [comment]
second this from FACN2 - people were testing the status code (which is actually already being tested in supertest expect.

I had to tell a few people they should be testing the body of the response and other things

**Comment by mattlub** [comment]
fixed by #22
