### ISSUE TITLE
remove 'TDD' from readme

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/express-and-testing-workshop#12]
The readme suggests that this is TDD, but writing tests after the code already exists is not "test-driven" development.

It's impossible to go through the red, green, refactor cycle when you already have the code.

> Use TDD to develop a backend server/API

> Express routes can be tested using TDD

> This repository provides you with a skeleton express server your task is to create tests for your express routes using TDD.

**Comment by BartBucknill** [comment]
Readme no longer suggests that this is a TDD workshop.
