### ISSUE TITLE
Should students be expected to change the server itself? If not, bug

### ISSUE THREAD

**Issue by m4v15** [foundersandcoders/express-and-testing-workshop#18]
At the moment the solution branch is different to the master branch. The queries file has been moved to a seperate folder and is also slightly different, below is 1 function which changes

Master:
https://github.com/foundersandcoders/express-and-testing-workshop/blob/master/server/routes/queries.js#L17-L20
Solution
https://github.com/foundersandcoders/express-and-testing-workshop/blob/solution-branch/server/queries/index.js#L18-L21

This isn't a massive issue I guess, but it causes a lot of confusion. The solution tests in the solution branch don't work on the master branch - that doesn't make much sense and if students have been working on the master branch (as they should) and then look at the tests on the solution branch they will (and have) got quite confused

**Comment by matthewdking** [comment]
To add to the confusion in the master branch there are two small errors [here](https://github.com/foundersandcoders/express-and-testing-workshop/blob/master/server/routes/queries.js#L18) and [here](https://github.com/foundersandcoders/express-and-testing-workshop/blob/master/server/routes/queries.js#L19).

The id is returned as an array with of objects.
```
 [ anonymous { id: 106 } ]
```
and also the query is never returned.

There are two ways to rewrite [these lines](https://github.com/foundersandcoders/express-and-testing-workshop/blob/master/server/routes/queries.js#L17-L20) which would fix these issues:
+ Option 1
```javascript
const getFacsterById = id => {
  const { id: facsterId } = id[0]; //Id is returned as an array of objects
  return db.query(`SELECT * FROM facsters WHERE facsters.id = $1`, facsterId);
};
```
+ Option 2
```javascript
const getFacsterById = idObj => {
  const [{ id }] = idObj;
  return db.query(`SELECT * FROM facsters WHERE facsters.id = $1`, [id]);
};
```

**Comment by BartBucknill** [comment]
@m4v15 @matthewdking Am I correct in thinking that both of these are not issues any longer? There is no longer a solution branch but rather a folder, and as far as I can make out the above mentioned queries are OK.
If so can we close this issue?

**Comment by m4v15** [comment]
Yeah good shout sorry, forgot to close the issue I guess
