### ISSUE TITLE
For Linux Users

### ISSUE THREAD

**Issue by Dragomirc** [foundersandcoders/express-and-testing-workshop#25]
Linux Users aren't able to to do this workshop, unless in the dbConnection.js file, you add  a database user and password(You can add the details of the user you created on week6). Please see below examples:

`const localDB = {
 
host: 'localhost',
 port: 5432,
  database: 'fac-express',
  user: '_XXXXXXXX_',
  password: '_XXXXXXX_'
};`

**Comment by mattlub** [comment]
yep, see #14, I'm gonna make a PR

**Comment by mattlub** [comment]
fixed in #26
