### ISSUE TITLE
Supertest & tape required in twice in solutions folder

### ISSUE THREAD

**Issue by astroash** [foundersandcoders/express-and-testing-workshop#27]
https://github.com/foundersandcoders/express-and-testing-workshop/blob/0b074b5f304f70738152c67890a6b1ec9f088697/solution-files/routes.test.js#L1-L2

☝️ this is never used

**Comment by m4v15** [comment]
As solution branches are being deprecated not sure this is a huge issue? Maybe this branch should just get deleted

**Comment by astroash** [comment]
Oh, sorry, I must have been asleep when I typed the title for this, it's in the solutions folder. It's a very minor thing, so isn't urgent. Just wanted to flag it :)
